"""milestone2_add_fasting_advisor_pet_cost_fields

Revision ID: 202eacfdfa1e
Revises: f1e2a3b4c5d6
Create Date: 2026-07-12 11:14:23.203152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '202eacfdfa1e'
down_revision: Union[str, Sequence[str], None] = 'm3_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 仅更新注释和索引，不删除现有列
    op.alter_column('ai_advisor_settings', 'advisor_style',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               comment='顾问风格: nutritionist/fitness_coach/tcm_healer/motivator',
               existing_comment='nutritionist/fitness_coach/tcm_healer/encouraging_friend',
               existing_nullable=False)
    op.alter_column('ai_advisor_settings', 'focus_goal',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               comment='关注目标: weight_loss/muscle_gain/balanced_health等',
               existing_comment='fat_loss/muscle_gain/sugar_control/wellness/balanced',
               existing_nullable=True)
    op.alter_column('ai_advisor_settings', 'focus_nutrient',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               comment='关注营养素: protein/fiber/vitamin_c等',
               existing_comment='calories/protein/carb/fat/micronutrient',
               existing_nullable=True)
    op.alter_column('ai_advisor_settings', 'response_style',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=True,
               comment='回复风格: professional/friendly/motivating/detailed',
               existing_comment='concise/detailed/example_rich')
    op.execute("DROP INDEX IF EXISTS idx_advisor_settings_user")
    op.execute("CREATE INDEX IF NOT EXISTS idx_ai_advisor_settings_user ON ai_advisor_settings (user_id)")
    op.execute("ALTER TABLE ai_advisor_settings DROP CONSTRAINT IF EXISTS ai_advisor_settings_user_id_fkey")
    op.alter_column('fasting_checkins', 'feeling',
               existing_type=sa.VARCHAR(length=30),
               comment='good / normal / tired / uncomfortable',
               existing_comment='good/normal/tired/uncomfortable',
               existing_nullable=False)
    op.alter_column('fasting_plans', 'plan_type',
               existing_type=sa.VARCHAR(length=20),
               comment='16_8 / 5_2 / basic_fasting',
               existing_comment='16_8/5_2/basic_fasting',
               existing_nullable=False)
    op.alter_column('fasting_plans', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active / paused / stopped / completed',
               existing_comment='active/paused/stopped/completed',
               existing_nullable=False)
    op.alter_column('food_records', 'source_tag',
               existing_type=sa.VARCHAR(length=20),
               comment='canteen/delivery/home/restaurant/snack/other',
               existing_nullable=True)
    op.execute("CREATE INDEX IF NOT EXISTS idx_food_records_source_tag ON food_records (source_tag)")
    # 注意：保留 reminders.fasting_plan_id 和 virtual_pet_states.custom_messages 列
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 回滚索引和注释修改
    op.execute("DROP INDEX IF EXISTS idx_food_records_source_tag")
    op.alter_column('food_records', 'source_tag',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='canteen/delivery/home/restaurant/snack/other',
               existing_nullable=True)
    op.alter_column('fasting_plans', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active/paused/stopped/completed',
               existing_comment='active / paused / stopped / completed',
               existing_nullable=False)
    op.alter_column('fasting_plans', 'plan_type',
               existing_type=sa.VARCHAR(length=20),
               comment='16_8/5_2/basic_fasting',
               existing_comment='16_8 / 5_2 / basic_fasting',
               existing_nullable=False)
    op.alter_column('fasting_checkins', 'feeling',
               existing_type=sa.VARCHAR(length=30),
               comment='good/normal/tired/uncomfortable',
               existing_comment='good / normal / tired / uncomfortable',
               existing_nullable=False)
    op.execute("ALTER TABLE ai_advisor_settings ADD CONSTRAINT ai_advisor_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE")
    op.execute("DROP INDEX IF EXISTS idx_ai_advisor_settings_user")
    op.execute("CREATE INDEX IF NOT EXISTS idx_advisor_settings_user ON ai_advisor_settings (user_id)")
    op.alter_column('ai_advisor_settings', 'response_style',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=False,
               comment='concise/detailed/example_rich',
               existing_comment='回复风格: professional/friendly/motivating/detailed')
    op.alter_column('ai_advisor_settings', 'focus_nutrient',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               comment='calories/protein/carb/fat/micronutrient',
               existing_comment='关注营养素: protein/fiber/vitamin_c等',
               existing_nullable=True)
    op.alter_column('ai_advisor_settings', 'focus_goal',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               comment='fat_loss/muscle_gain/sugar_control/wellness/balanced',
               existing_comment='关注目标: weight_loss/muscle_gain/balanced_health等',
               existing_nullable=True)
    op.alter_column('ai_advisor_settings', 'advisor_style',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               comment='nutritionist/fitness_coach/tcm_healer/encouraging_friend',
               existing_comment='顾问风格: nutritionist/fitness_coach/tcm_healer/motivator',
               existing_nullable=False)
    # ### end Alembic commands ###
