"""add exercise_name to exercise_records

Revision ID: 948564492a8a
Revises: b4c3
Create Date: 2026-06-12 11:23:46.424673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948564492a8a'
down_revision: Union[str, Sequence[str], None] = 'b4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_records', sa.Column('exercise_name', sa.String(length=100), nullable=True))
    op.create_index('idx_exercise_user_date', 'exercise_records', ['user_id', 'record_date'], unique=False)
    op.create_index('idx_notif_resp_user_reminder', 'notification_responses', ['user_id', 'reminder_id'], unique=False)
    op.create_index('idx_notif_resp_user_time', 'notification_responses', ['user_id', 'responded_at'], unique=False)
    op.create_index('idx_reminders_user_type_enabled', 'reminders', ['user_id', 'reminder_type', 'is_enabled', 'remind_time'], unique=False)
    op.create_index('idx_water_user_time', 'water_intake_records', ['user_id', 'record_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_water_user_time', table_name='water_intake_records')
    op.drop_index('idx_reminders_user_type_enabled', table_name='reminders')
    op.drop_index('idx_notif_resp_user_time', table_name='notification_responses')
    op.drop_index('idx_notif_resp_user_reminder', table_name='notification_responses')
    op.drop_index('idx_exercise_user_date', table_name='exercise_records')
    op.drop_column('exercise_records', 'exercise_name')
    # ### end Alembic commands ###
