"""add record_time to food_records

Revision ID: cc7c07bf9f95
Revises: 948564492a8a
Create Date: 2026-06-12 12:08:27.300942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7c07bf9f95'
down_revision: Union[str, Sequence[str], None] = '948564492a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_records', sa.Column('record_time', sa.DateTime(), nullable=True, comment='餐食的实际用餐时间（用户选择或默认当前时间）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_records', 'record_time')
    # ### end Alembic commands ###
