"""milestone1 new tables and fields

Revision ID: e6a322b5c6ba
Revises: a1cb58018622
Create Date: 2026-05-06 22:41:02.062547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6a322b5c6ba'
down_revision: Union[str, Sequence[str], None] = 'a1cb58018622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellness_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('recommended_foods', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('avoid_foods', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('applicable_constitutions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.Column('solar_term', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_knowledge_id'), 'wellness_knowledge', ['id'], unique=False)
    op.create_table('exercise_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Float(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_records_id'), 'exercise_records', ['id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=10), nullable=False),
    sa.Column('remind_time', sa.Time(), nullable=False),
    sa.Column('repeat_days', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('virtual_pet_status', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_table('water_intake_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('record_time', sa.DateTime(), nullable=False),
    sa.Column('drink_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_intake_records_id'), 'water_intake_records', ['id'], unique=False)
    op.create_table('notification_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_responses_id'), 'notification_responses', ['id'], unique=False)
    op.add_column('food_records', sa.Column('from_source', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('crowd_tag', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('constitution_type', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('daily_water_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'daily_water_goal')
    op.drop_column('user_profiles', 'constitution_type')
    op.drop_column('user_profiles', 'crowd_tag')
    op.drop_column('food_records', 'from_source')
    op.drop_index(op.f('ix_notification_responses_id'), table_name='notification_responses')
    op.drop_table('notification_responses')
    op.drop_index(op.f('ix_water_intake_records_id'), table_name='water_intake_records')
    op.drop_table('water_intake_records')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_exercise_records_id'), table_name='exercise_records')
    op.drop_table('exercise_records')
    op.drop_index(op.f('ix_wellness_knowledge_id'), table_name='wellness_knowledge')
    op.drop_table('wellness_knowledge')
    # ### end Alembic commands ###
