"""add_invite_code_to_users

Revision ID: f6936fa8f76a
Revises: 439ff5e39b69
Create Date: 2026-08-04 20:28:54.662017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6936fa8f76a'
down_revision: Union[str, Sequence[str], None] = '439ff5e39b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_device_tokens_user_active'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.alter_column('ai_advisor_settings', 'pet_advisor_style',
               existing_type=sa.VARCHAR(length=50),
               comment='宠物顾问风格: vet_assistant/pet_nutritionist/pet_caregiver',
               existing_nullable=True,
               existing_server_default=sa.text("'vet_assistant'::character varying"))
    op.alter_column('ai_advisor_settings', 'pet_focus_goal',
               existing_type=sa.VARCHAR(length=255),
               comment='宠物关注目标: weight_management/nutrition_balance等',
               existing_nullable=True)
    op.alter_column('exercise_records', 'distance_km',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='运动距离(公里)，适用于跑步/骑行/游泳/步行',
               existing_nullable=True)
    op.drop_index(op.f('idx_fasting_checkin_fasting_day'), table_name='fasting_checkins')
    op.alter_column('pet_food_database', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment='dry_food/wet_food/snack/fresh',
               existing_comment='dry_food/wet_food/snack',
               existing_nullable=True)
    op.create_index(op.f('ix_pet_food_database_user_id'), 'pet_food_database', ['user_id'], unique=False)
    op.create_foreign_key(None, 'pet_food_database', 'users', ['user_id'], ['id'])
    op.alter_column('pet_profiles', 'avatar_url',
               existing_type=sa.TEXT(),
               comment='AI生成的头像URL（签名URL可能超2000字符）',
               existing_nullable=True)
    op.alter_column('pet_unlockables', 'unlock_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='skin/action/effect',
               existing_nullable=False)
    op.alter_column('reminders', 'fasting_plan_id',
               existing_type=sa.INTEGER(),
               comment='关联断食计划',
               existing_nullable=True)
    op.create_foreign_key(None, 'reminders', 'fasting_plans', ['fasting_plan_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('invite_code', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_constraint(op.f('uq_users_email_hash'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_phone_hash'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    op.alter_column('virtual_pet_states', 'mood',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='normal/happy/hungry/anxious/weak',
               existing_nullable=False)
    op.alter_column('virtual_pet_states', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='状态版本号，硬件轮询用',
               existing_nullable=False)
    op.alter_column('virtual_pet_states', 'custom_messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='用户自定义宠物提示语，key为场景名称',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('virtual_pet_states', 'pet_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_pet_states', sa.Column('pet_names', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"default": "桌宠一", "christine": "桌宠二"}\'::jsonb'), autoincrement=False, nullable=True))
    op.alter_column('virtual_pet_states', 'custom_messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='用户自定义宠物提示语，key为场景名称',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('virtual_pet_states', 'version',
               existing_type=sa.INTEGER(),
               comment='状态版本号，硬件轮询用',
               existing_nullable=False)
    op.alter_column('virtual_pet_states', 'mood',
               existing_type=sa.VARCHAR(length=20),
               comment='normal/happy/hungry/anxious/weak',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=False)
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_users_phone_hash'), 'users', ['phone_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_email_hash'), 'users', ['email_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'invite_code')
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.alter_column('reminders', 'fasting_plan_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联断食计划',
               existing_nullable=True)
    op.alter_column('pet_unlockables', 'unlock_type',
               existing_type=sa.VARCHAR(length=20),
               comment='skin/action/effect',
               existing_nullable=False)
    op.alter_column('pet_profiles', 'avatar_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='AI生成的头像URL（签名URL可能超2000字符）',
               existing_nullable=True)
    op.drop_constraint(None, 'pet_food_database', type_='foreignkey')
    op.drop_index(op.f('ix_pet_food_database_user_id'), table_name='pet_food_database')
    op.alter_column('pet_food_database', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment='dry_food/wet_food/snack',
               existing_comment='dry_food/wet_food/snack/fresh',
               existing_nullable=True)
    op.create_index(op.f('idx_fasting_checkin_fasting_day'), 'fasting_checkins', ['plan_id', 'is_fasting_day'], unique=False)
    op.alter_column('exercise_records', 'distance_km',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='运动距离(公里)，适用于跑步/骑行/游泳/步行',
               existing_nullable=True)
    op.alter_column('ai_advisor_settings', 'pet_focus_goal',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='宠物关注目标: weight_management/nutrition_balance等',
               existing_nullable=True)
    op.alter_column('ai_advisor_settings', 'pet_advisor_style',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='宠物顾问风格: vet_assistant/pet_nutritionist/pet_caregiver',
               existing_nullable=True,
               existing_server_default=sa.text("'vet_assistant'::character varying"))
    op.create_table('device_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='FCM device token'),
    sa.Column('platform', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='android / ios'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否有效'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('device_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('device_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('idx_device_tokens_user_active'), 'device_tokens', ['user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###
