"""add devices table

Revision ID: ff905333d9b6
Revises: b7e9c1f0a4d2
Create Date: 2026-08-11 12:22:00.096062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff905333d9b6'
down_revision: Union[str, Sequence[str], None] = 'b7e9c1f0a4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_sync_log_user'), table_name='offline_sync_logs')
    op.drop_index(op.f('ix_offline_sync_logs_id'), table_name='offline_sync_logs')
    op.drop_table('offline_sync_logs')
    op.drop_index(op.f('idx_device_tokens_user_active'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('idx_pet_unlock_user_type'), table_name='pet_unlocks')
    op.drop_index(op.f('ix_pet_unlocks_id'), table_name='pet_unlocks')
    op.drop_table('pet_unlocks')
    op.alter_column('ai_advisor_settings', 'pet_advisor_style',
               existing_type=sa.VARCHAR(length=50),
               comment='宠物顾问风格: vet_assistant/pet_nutritionist/pet_caregiver',
               existing_nullable=True,
               existing_server_default=sa.text("'vet_assistant'::character varying"))
    op.alter_column('ai_advisor_settings', 'pet_focus_goal',
               existing_type=sa.VARCHAR(length=255),
               comment='宠物关注目标: weight_management/nutrition_balance等',
               existing_nullable=True)
    op.alter_column('exercise_records', 'distance_km',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               comment='运动距离(公里)，适用于跑步/骑行/游泳/步行',
               existing_nullable=True)
    op.alter_column('fasting_checkins', 'is_fasting_day',
               existing_type=sa.BOOLEAN(),
               comment='当天是否是断食日',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('fasting_plans', 'start_weight',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               type_=sa.Numeric(precision=5, scale=2),
               comment='计划开始时的体重(kg)',
               existing_nullable=True)
    op.alter_column('fasting_plans', 'fasting_days',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='断食日列表，如[0,2]表示周一、周三',
               existing_nullable=True)
    op.alter_column('food_records', 'record_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='餐食的实际用餐时间（用户选择或默认当前时间）',
               existing_nullable=True)
    op.drop_index(op.f('ix_food_records_source_tag'), table_name='food_records')
    op.create_foreign_key(None, 'food_records', 'users', ['recorded_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('hardware_quick_buttons', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.alter_column('hardware_quick_buttons', 'label',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('hardware_quick_buttons', 'calories',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('hardware_quick_buttons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_hw_button_user_idx'), 'hardware_quick_buttons', type_='unique')
    op.create_index('idx_hw_buttons_user', 'hardware_quick_buttons', ['user_id', 'button_index'], unique=True)
    op.create_foreign_key(None, 'hardware_quick_buttons', 'pet_profiles', ['pet_id'], ['id'])
    op.drop_column('hardware_quick_buttons', 'updated_at')
    op.alter_column('pet_avatars', 'base_image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'emotion_happy_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'emotion_normal_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'emotion_hungry_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'emotion_weak_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'gif_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.add_column('pet_food_database', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('pet_food_database', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment='dry_food/wet_food/snack/fresh',
               existing_comment='dry_food/wet_food/snack',
               existing_nullable=True)
    op.create_index(op.f('ix_pet_food_database_user_id'), 'pet_food_database', ['user_id'], unique=False)
    op.create_foreign_key(None, 'pet_food_database', 'users', ['user_id'], ['id'])
    op.alter_column('pet_profiles', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               comment='AI生成的头像URL（签名URL可能超2000字符）',
               existing_nullable=True)
    op.alter_column('pet_unlockables', 'unlock_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='skin/action/effect',
               existing_nullable=False)
    op.alter_column('reminders', 'fasting_plan_id',
               existing_type=sa.INTEGER(),
               comment='关联断食计划',
               existing_comment='关联轻断食计划ID（M2）',
               existing_nullable=True)
    op.drop_constraint(op.f('reminders_fasting_plan_id_fkey'), 'reminders', type_='foreignkey')
    op.create_foreign_key(None, 'reminders', 'fasting_plans', ['fasting_plan_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user_profiles', 'target_calories',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_wechat_openid'), table_name='users')
    op.drop_index(op.f('idx_wechat_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_constraint(op.f('uq_users_email_hash'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_phone_hash'), 'users', type_='unique')
    op.drop_constraint(op.f('users_wechat_openid_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_wechat_unionid_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.drop_column('users', 'wechat_unionid')
    op.drop_column('users', 'wechat_openid')
    op.alter_column('virtual_pet_states', 'mood',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='normal/happy/hungry/anxious/weak',
               existing_nullable=False)
    op.alter_column('virtual_pet_states', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='状态版本号，硬件轮询用',
               existing_nullable=False)
    op.alter_column('virtual_pet_states', 'custom_messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='用户自定义宠物提示语，key为场景名称',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('virtual_pet_states', 'custom_messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='用户自定义宠物提示语，key为场景名称',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('virtual_pet_states', 'version',
               existing_type=sa.INTEGER(),
               comment='状态版本号，硬件轮询用',
               existing_nullable=False)
    op.alter_column('virtual_pet_states', 'mood',
               existing_type=sa.VARCHAR(length=20),
               comment='normal/happy/hungry/anxious/weak',
               existing_nullable=False)
    op.add_column('users', sa.Column('wechat_openid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('wechat_unionid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=False)
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=False)
    op.create_unique_constraint(op.f('users_wechat_unionid_key'), 'users', ['wechat_unionid'])
    op.create_unique_constraint(op.f('users_wechat_openid_key'), 'users', ['wechat_openid'])
    op.create_unique_constraint(op.f('uq_users_phone_hash'), 'users', ['phone_hash'])
    op.create_unique_constraint(op.f('uq_users_email_hash'), 'users', ['email_hash'])
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('idx_wechat_unionid'), 'users', ['wechat_unionid'], unique=False)
    op.create_index(op.f('idx_wechat_openid'), 'users', ['wechat_openid'], unique=False)
    op.alter_column('user_profiles', 'target_calories',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.create_foreign_key(op.f('reminders_fasting_plan_id_fkey'), 'reminders', 'fasting_plans', ['fasting_plan_id'], ['id'])
    op.alter_column('reminders', 'fasting_plan_id',
               existing_type=sa.INTEGER(),
               comment='关联轻断食计划ID（M2）',
               existing_comment='关联断食计划',
               existing_nullable=True)
    op.alter_column('pet_unlockables', 'unlock_type',
               existing_type=sa.VARCHAR(length=20),
               comment='skin/action/effect',
               existing_nullable=False)
    op.alter_column('pet_profiles', 'avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='AI生成的头像URL（签名URL可能超2000字符）',
               existing_nullable=True)
    op.drop_constraint(None, 'pet_food_database', type_='foreignkey')
    op.drop_index(op.f('ix_pet_food_database_user_id'), table_name='pet_food_database')
    op.alter_column('pet_food_database', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment='dry_food/wet_food/snack',
               existing_comment='dry_food/wet_food/snack/fresh',
               existing_nullable=True)
    op.drop_column('pet_food_database', 'user_id')
    op.alter_column('pet_avatars', 'gif_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'emotion_weak_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'emotion_hungry_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'emotion_normal_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'emotion_happy_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('pet_avatars', 'base_image_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('hardware_quick_buttons', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hardware_quick_buttons', type_='foreignkey')
    op.drop_index('idx_hw_buttons_user', table_name='hardware_quick_buttons')
    op.create_unique_constraint(op.f('uq_hw_button_user_idx'), 'hardware_quick_buttons', ['user_id', 'button_index'])
    op.alter_column('hardware_quick_buttons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hardware_quick_buttons', 'calories',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('hardware_quick_buttons', 'label',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('hardware_quick_buttons', 'pet_id')
    op.drop_constraint(None, 'food_records', type_='foreignkey')
    op.create_index(op.f('ix_food_records_source_tag'), 'food_records', ['source_tag'], unique=False)
    op.alter_column('food_records', 'record_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='餐食的实际用餐时间（用户选择或默认当前时间）',
               existing_nullable=True)
    op.alter_column('fasting_plans', 'fasting_days',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='断食日列表，如[0,2]表示周一、周三',
               existing_nullable=True)
    op.alter_column('fasting_plans', 'start_weight',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=5, scale=1),
               comment=None,
               existing_comment='计划开始时的体重(kg)',
               existing_nullable=True)
    op.alter_column('fasting_checkins', 'is_fasting_day',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='当天是否是断食日',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('exercise_records', 'distance_km',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               comment=None,
               existing_comment='运动距离(公里)，适用于跑步/骑行/游泳/步行',
               existing_nullable=True)
    op.alter_column('ai_advisor_settings', 'pet_focus_goal',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='宠物关注目标: weight_management/nutrition_balance等',
               existing_nullable=True)
    op.alter_column('ai_advisor_settings', 'pet_advisor_style',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='宠物顾问风格: vet_assistant/pet_nutritionist/pet_caregiver',
               existing_nullable=True,
               existing_server_default=sa.text("'vet_assistant'::character varying"))
    op.create_table('pet_unlocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unlock_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('unlock_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('required_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('required_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_unlocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('pet_unlocks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pet_unlocks_pkey')),
    sa.UniqueConstraint('user_id', 'unlock_type', 'unlock_key', name=op.f('uq_pet_unlock_user_type_key'))
    )
    op.create_index(op.f('ix_pet_unlocks_id'), 'pet_unlocks', ['id'], unique=False)
    op.create_index(op.f('idx_pet_unlock_user_type'), 'pet_unlocks', ['user_id', 'unlock_type'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='FCM device token'),
    sa.Column('platform', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='android / ios'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否有效'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('device_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('device_tokens_token_key'))
    )
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('idx_device_tokens_user_active'), 'device_tokens', ['user_id', 'is_active'], unique=False)
    op.create_table('offline_sync_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('synced_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sync_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('offline_sync_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('offline_sync_logs_pkey'))
    )
    op.create_index(op.f('ix_offline_sync_logs_id'), 'offline_sync_logs', ['id'], unique=False)
    op.create_index(op.f('idx_sync_log_user'), 'offline_sync_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###
